---
title: "CatAct V1"
author: "Martin Zettersten"
date: "2023-01-17"
output: html_document
---

```{r setup}
library(here)
library(tidyverse)
library(ggplot2)
library(viridisLite)
library(lme4)
library(ggstance)
library(cowplot)
library(AICcmodavg)
library(RColorBrewer)
library(jsonlite)
library(tidyjson)
library(rlang)
source("helper.R")

data_path <- here("..","..","data","v1","processed", "catact-v1-alldata-anonymized.csv")
figure_path <- here("figures")
```

# Data Processing

## Read in data

```{r}
d <- read_csv(data_path)
```

## Process hypernym

```{r}
temp_sampling_images <- d %>%
  filter(trial_type == "html-button-response-catact") %>%
  select(subject,current_training_label,current_category_label_level, current_category_kind,current_category_training_level,shuffled_sampling_images,sampling_image_words) %>%
  mutate(image_array = map(shuffled_sampling_images, ~ convert_array(.,column_name="image_name"))) %>%
  unnest(image_array) 

temp_sampling_labels <- d %>%
  filter(trial_type == "html-button-response-catact") %>%
  select(subject,current_training_label,current_category_label_level, current_category_kind,current_category_training_level,shuffled_sampling_images,sampling_image_words) %>%
  mutate(label_array = map(sampling_image_words, ~ convert_array(.,column_name="image_label"))) %>%
  unnest(label_array)

sampling_assignment_long <- temp_sampling_images %>%
  left_join(temp_sampling_labels) %>%
  mutate(
    image_category  = case_when(
      str_detect(image_name,"ani") ~ "animals",
      str_detect(image_name,"veg") ~ "vegetables",
      str_detect(image_name,"veh") ~ "vehicles",
    )
  )

hypernym_categories <- sampling_assignment_long %>%
  filter(current_category_label_level=="hypernym") %>%
  mutate(
    hypernym_category = case_when(
      current_training_label == image_label &
        image_category != current_category_kind ~ image_category
    )
  ) %>%
  filter(!is.na(hypernym_category)) %>%
  distinct(subject,current_training_label,current_category_label_level, current_category_kind,current_category_training_level,hypernym_category)

d <- d %>%
  left_join(hypernym_categories) %>%
  relocate(hypernym_category,.after = current_category_kind)
  
  
```



## Process survey/ nested responses

```{r}
#unnesting json
survey_responses <- d %>% 
  filter(trial_type %in% c("survey-html-form","survey-text","survey-multi-choice","survey-multi-select")) %>%
  select(subject,trial_type,current_category_training_level,current_category_kind,response) %>%
  mutate(json = map(response, ~ fromJSON(.) %>% as.data.frame())) %>% 
  unnest(json) %>%
  group_by(subject) %>%
  fill(age,gender,country,language,other_languages,race,education,strategy,choice_strategy,comments,.direction = "downup") %>%
  select(-response,-trial_type) %>%
  filter(!is.na(current_category_training_level)) %>%
  fill(name_check,.direction = "down") %>%
  fill(word_meaning,.direction = "up") %>%
  distinct()

d <- d %>%
  left_join(survey_responses)
```

## Process sampling

```{r}
# process sampled image
d <- d %>%
  mutate(
    sampled_imagename = str_remove(sampled_image,"stims/"),
    sampled_imagelabel = str_remove(sampled_imagename,".jpg")
  ) %>%
  rowwise() %>%
  mutate(
    sampled_category_kind_short = unlist(str_split(sampled_imagelabel,"_"))[1],
    sampled_category_level = str_replace_all(unlist(str_split(sampled_imagelabel,"_"))[3], "[:digit:]","")
  ) %>%
  mutate(
    sampled_category_kind  = case_when(
      sampled_category_kind_short == "ani" ~ "animals",
      sampled_category_kind_short == "veg" ~ "vegetables",
      sampled_category_kind_short == "veh" ~ "vehicles",
    )
  ) %>%
  mutate(
    within_category_sample = ifelse(sampled_category_kind == current_category_kind,1,0),
    within_category_sample_f =  ifelse(sampled_category_kind == current_category_kind,"within-category","other-category"),
  ) %>%
  mutate(
    sampled_category_level_kind_info=ifelse(within_category_sample==0,"outside_category",sampled_category_level)
  )
```

```{r}
sampling_data <- d %>%
  filter(trial_type == "html-button-response-catact") %>%
  select(subject,current_training_images,current_training_label,current_category_label_level, current_category_kind,current_category_training_level,sampled_image, sampled_label,sampled_imagename,sampled_imagelabel,sampled_category_kind_short,sampled_category_kind,sampled_category_level,within_category_sample,within_category_sample_f,sampled_category_level_kind_info)

#categorizing choice types
sampling_data <- sampling_data %>%
  mutate(
    sampling_choice_consistent = case_when(
      current_category_training_level == "narrow" & sampled_category_level_kind_info == "sub" ~ "consistent",
      current_category_training_level == "intermediate" & sampled_category_level_kind_info == "sub" ~ "consistent",
      current_category_training_level == "intermediate" & sampled_category_level_kind_info == "bas" ~ "consistent",
      current_category_training_level == "broad" & sampled_category_level_kind_info == "sub" ~ "consistent",
      current_category_training_level == "broad" & sampled_category_level_kind_info == "bas" ~ "consistent",
      current_category_training_level == "broad" & sampled_category_level_kind_info == "sup" ~ "consistent",
      TRUE ~ "inconsistent"
    ),
    sampling_choice_narrowly_constraining = case_when(
      current_category_training_level == "narrow" & sampled_category_level_kind_info == "bas" ~ "constraining",
      current_category_training_level == "intermediate" & sampled_category_level_kind_info == "sup" ~ "constraining",
      current_category_training_level == "broad" & sampled_category_level_kind_info == "outside_category" ~ "constraining",
      TRUE ~ sampling_choice_consistent
    )
  )

```

## Test data

```{r}
test_array <- d %>% 
  filter(trial_type == "html-button-response-catact") %>%
  select(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,hypernym_category,final_choice_array) %>%
  mutate(choices = map(final_choice_array, ~ convert_array(.,column_name="test_choice"))) %>%
  unnest(choices) 

test_array_clean <- test_array %>%
  mutate(
    test_choice_type = case_when(
      str_detect(test_choice,"sup") ~ "superordinate",
      str_detect(test_choice,"bas") ~ "basic",
      str_detect(test_choice,"sub") ~ "subordinate"
    )
  ) %>%
  mutate(
    test_choice_category = case_when(
      str_detect(test_choice,"ani") ~ "animals",
      str_detect(test_choice,"veg") ~ "vegetables",
      str_detect(test_choice,"veh") ~ "vehicles"
    )
  ) %>%
  mutate(
    test_choice_match_category = ifelse(test_choice_category == current_category_kind,1,0),
    test_choice_match_ground_truth_category = case_when(
      current_category_label_level == "hypernym" & test_choice_category == hypernym_category ~ 1,
      test_choice_category == current_category_kind ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    test_choice_type_training_consistent = case_when(
      current_category_training_level == "narrow" &  test_choice_type %in% c("subordinate") & test_choice_match_category == 1 ~ 1,
      current_category_training_level == "intermediate" &  test_choice_type %in% c("subordinate","basic") & test_choice_match_category == 1 ~ 1,
      current_category_training_level == "broad" &  test_choice_type %in% c("subordinate","basic","superordinate")& test_choice_match_category == 1 ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    test_choice_type_label_consistent = case_when(
      current_category_label_level == "narrow" &  test_choice_type %in% c("subordinate") & test_choice_match_category == 1 ~ 1,
      current_category_label_level == "intermediate" &  test_choice_type %in% c("subordinate","basic") & test_choice_match_category == 1 ~ 1,
      current_category_label_level == "broad" & test_choice_match_category == 1 ~ 1,
      current_category_label_level == "hypernym" &  test_choice_match_ground_truth_category == 1 ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    total_number_correct_options = case_when(
      current_category_label_level == "narrow" ~ 2,
      current_category_label_level == "intermediate" ~ 4,
      current_category_label_level == "broad" ~ 8,
      current_category_label_level == "hypernym" ~ 16
    )
  )

subj_test_accuracy <- test_array_clean %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  summarize(
    total_choices = n(),
    ground_truth_correct_choices = sum(test_choice_type_label_consistent),
    ground_truth_incorrect_choices = sum(test_choice_type_label_consistent==0),
    training_consistent_choices = sum(test_choice_type_training_consistent),
    training_inconsistent_choices = sum(test_choice_type_training_consistent==0),
    training_category_match_subordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "subordinate"),
    training_category_match_basic_choices = sum(test_choice_match_category==1 & test_choice_type == "basic"),
    training_category_match_superordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "superordinate"),
    training_category_match_subordinate_percent = training_category_match_subordinate_choices/2,
    training_category_match_basic_percent = training_category_match_basic_choices/2,
    training_category_match_superordinate_percent = training_category_match_superordinate_choices/4
  )

subj_test_accuracy_long <- subj_test_accuracy %>%
  select(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options,training_category_match_subordinate_percent,training_category_match_basic_percent,training_category_match_superordinate_percent) %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  pivot_longer(cols=training_category_match_subordinate_percent:training_category_match_superordinate_percent,names_to = "choice_type",values_to = "percent_chosen")

subj_test_accuracy_long <- subj_test_accuracy_long %>%
  left_join(sampling_data)

overall_accuracy <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(current_category_training_level,choice_type) %>%
summarize(
  N=n(),
  average_percent=mean(percent_chosen)
) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(current_category_training_level,current_category_label_level,choice_type) %>%
summarize(
  N=n(),
  average_percent=mean(percent_chosen)
) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level_sampling <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(sampling_choice_narrowly_constraining,current_category_training_level,current_category_label_level,choice_type,) %>%
summarize(
  N=n(),
  average_percent=mean(percent_chosen)
) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )
  
```

## Test data - all images

```{r}
test_array_options <- d %>% 
  filter(trial_type == "html-button-response-catact") %>%
  select(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,hypernym_category,shuffled_test_images,final_choice_array) %>%
  mutate(test_options = map(shuffled_test_images, ~ convert_array(.,column_name="test_image"))) %>%
  unnest(test_options) 

test_array_options <- test_array_options %>%
  mutate(
    is_chosen = case_when(
      str_detect(final_choice_array,test_image) ~ 1,
      TRUE ~ 0
  )
  )

test_array_options_clean <- test_array_options %>%
  mutate(
    test_image_type = case_when(
      str_detect(test_image,"sup") ~ "superordinate",
      str_detect(test_image,"bas") ~ "basic",
      str_detect(test_image,"sub") ~ "subordinate"
    )
  ) %>%
  mutate(
    test_image_category = case_when(
      str_detect(test_image,"ani") ~ "animals",
      str_detect(test_image,"veg") ~ "vegetables",
      str_detect(test_image,"veh") ~ "vehicles"
    )
  ) %>%
  mutate(
    test_image_match_category = ifelse(test_image_category == current_category_kind,1,0),
    test_image_match_ground_truth_category = case_when(
      current_category_label_level == "hypernym" & test_image_category == hypernym_category ~ 1,
      test_image_category == current_category_kind ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    test_image_type_training_consistent = case_when(
      current_category_training_level == "narrow" &  test_image_type %in% c("subordinate") & test_image_match_category == 1 ~ 1,
      current_category_training_level == "intermediate" &  test_image_type %in% c("subordinate","basic") & test_image_match_category == 1 ~ 1,
      current_category_training_level == "broad" &  test_image_type %in% c("subordinate","basic","superordinate")& test_image_match_category == 1 ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    test_image_type_label_consistent = case_when(
      current_category_label_level == "narrow" &  test_image_type %in% c("subordinate") & test_image_match_category == 1 ~ 1,
      current_category_label_level == "intermediate" &  test_image_type %in% c("subordinate","basic") & test_image_match_category == 1 ~ 1,
      current_category_label_level == "broad" & test_image_match_category == 1 ~ 1,
      current_category_label_level == "hypernym" &  test_image_match_ground_truth_category == 1 ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    total_number_correct_options_label = case_when(
      current_category_label_level == "narrow" ~ 2,
      current_category_label_level == "intermediate" ~ 4,
      current_category_label_level == "broad" ~ 8,
      current_category_label_level == "hypernym" ~ 16
    ),
    total_number_correct_options_training = case_when(
      current_category_training_level == "narrow" ~ 2,
      current_category_training_level == "intermediate" ~ 4,
      current_category_training_level == "broad" ~ 8
    )
  ) %>%
  mutate(
    is_match_to_training = case_when(
      test_image_type_training_consistent == is_chosen ~ 1,
      TRUE ~ 0
    ),
    is_match_to_label = case_when(
      test_image_type_label_consistent == is_chosen ~ 1,
      TRUE ~ 0
    ),
    label_matches_training = case_when(
      current_category_training_level == current_category_label_level ~ 1,
      TRUE ~ 0
    )
  ) %>%
  mutate(
    hit_training = ifelse(test_image_type_training_consistent == 1, is_match_to_training,NA),
    hit_label = ifelse(test_image_type_label_consistent == 1, is_match_to_label,NA),
    false_alarm_training = ifelse(test_image_type_training_consistent == 0,1-is_match_to_training,NA),
    false_alarm_label = ifelse(test_image_type_label_consistent == 0,1-is_match_to_label,NA),
  )

subj_test_accuracy_all <- test_array_options_clean %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options_label,total_number_correct_options_training) %>%
  summarize(
    accuracy_training = mean(is_match_to_training, na.rm=TRUE),
    accuracy_label = mean(is_match_to_label,na.rm=TRUE),
    hit_rate_training = mean(hit_training,na.rm=TRUE),
    hit_rate_label = mean(hit_label,na.rm=TRUE),
    false_alarm_rate_training = mean(false_alarm_training,na.rm=TRUE),
    false_alarm_rate_label = mean(false_alarm_label,na.rm=TRUE)
  ) %>%
  mutate(
    hit_rate_training_adj= case_when(
      hit_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      hit_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      TRUE ~ hit_rate_training
    ),
    hit_rate_label_adj= case_when(
      hit_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      hit_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      TRUE ~ hit_rate_label
    ),
    false_alarm_rate_training_adj= case_when(
      false_alarm_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      false_alarm_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      TRUE ~ false_alarm_rate_training
    ),
    false_alarm_rate_label_adj= case_when(
      false_alarm_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      false_alarm_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      TRUE ~ false_alarm_rate_label
    )
  ) %>%
  mutate(
    dprime_training=qnorm(hit_rate_training_adj) - qnorm(false_alarm_rate_training_adj),
    dprime_label=qnorm(hit_rate_label_adj) - qnorm(false_alarm_rate_label_adj),
    c_training=-.5*(qnorm(hit_rate_training_adj) + qnorm(false_alarm_rate_training_adj)),
    c_label=-.5*(qnorm(hit_rate_label_adj) + qnorm(false_alarm_rate_label_adj)))



subj_test_accuracy_all <- subj_test_accuracy_all %>%
  left_join(sampling_data)

overall_accuracy_label_level_sampling_all <- subj_test_accuracy_all %>%
  ungroup() %>%
  group_by(sampling_choice_narrowly_constraining,current_category_training_level,current_category_label_level) %>%
summarize(
  N=n(),
  average_dprime_training=mean(dprime_training),
  average_dprime_label=mean(dprime_label)
) 
```


# Descriptive Plots

## Sampling

```{r}
sampling_data$sampled_category_level_kind_info_ord <- factor(sampling_data$sampled_category_level_kind_info,levels=c("sub","bas","sup","outside_category"))

sampling_data$current_category_training_level_ord <- factor(sampling_data$current_category_training_level,levels=c("narrow","intermediate","broad"))

ggplot(sampling_data,aes(x=sampled_category_level_kind_info_ord,color=within_category_sample_f,fill=within_category_sample_f))+
  geom_histogram(stat="count")+
  scale_fill_brewer(type="qual",palette="Set1")+
  scale_color_brewer(type="qual",palette="Set1")+
  facet_wrap(~current_category_training_level_ord)+
  scale_x_discrete(
    name = "Sampled Category Level",
    labels = c("subordinate","basic","superordinate","other category")
  )+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))+
  theme(legend.position="none")+
  ylab("Number of Choices")

ggsave(here(figure_path,"overall_sampling.pdf"))

ggplot(sampling_data,aes(x=sampled_category_level_kind_info_ord,color=within_category_sample_f,fill=within_category_sample_f))+
  geom_histogram(stat="count")+
  scale_fill_brewer(type="qual",palette="Set1")+
  scale_color_brewer(type="qual",palette="Set1")+
  facet_wrap(~current_category_training_level_ord+current_category_kind)+
  scale_x_discrete(
    name = "Sampled Category Level",
    labels = c("subordinate","basic","superordinate","other category")
  )+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))+
  theme(legend.position="none")+
  ylab("Number of Choices")
```

## Test

```{r}
overall_accuracy$choice_type_ord <- factor(overall_accuracy$choice_type,levels=c("subordinate","basic","superordinate"))

overall_accuracy$current_category_training_level_ord <- factor(overall_accuracy$current_category_training_level,levels=c("narrow","intermediate","broad"))

overall_accuracy_label_level$choice_type_ord <- factor(overall_accuracy_label_level$choice_type,levels=c("subordinate","basic","superordinate"))

overall_accuracy_label_level$current_category_label_level_ord <- factor(overall_accuracy_label_level$current_category_label_level,levels=c("narrow","intermediate","broad","hypernym"))

ggplot(overall_accuracy, aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p1 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="narrow"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p2 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="intermediate"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p3 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="broad"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

plot_grid(p1,p2,p3,nrow=3)
  
```

## Sampling & Test

```{r}
ggplot(overall_accuracy_label_level_sampling_all,aes(sampling_choice_narrowly_constraining,average_dprime_training))+
  geom_boxplot()+
  geom_point()+
  facet_wrap(~current_category_training_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(overall_accuracy_label_level_sampling_all,aes(sampling_choice_narrowly_constraining,average_dprime_label))+
  geom_boxplot()+
  geom_point()+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))
```

