---
title: "CatAct V1"
author: "Martin Zettersten"
date: "2023-01-17"
output: html_document
---

```{r setup}
library(here)
library(tidyverse)
library(ggplot2)
library(viridisLite)
library(lme4)
library(ggstance)
library(cowplot)
library(AICcmodavg)
library(RColorBrewer)
library(jsonlite)
library(tidyjson)
library(rlang)
library(car)
source("helper.R")

data_path <- here("..","..","data","v1","processed", "catact-v1-alldata-processed.csv")
sampling_data_path <- here("..","..","data","v1","processed", "catact-v1-sampling-data.csv")
test_data_path <- here("..","..","data","v1","processed", "catact-v1-test-data.csv")
test_data_long_path <- here("..","..","data","v1","processed", "catact-v1-test-data-long.csv")
figure_path <- here("figures")
```

# Data Processing

## Read in data

```{r}
d <- read_csv(data_path)
sampling_data <- read_csv(sampling_data_path)
test_array_clean <- read_csv(test_data_path)
test_array_options_clean <- read_csv(test_data_long_path)
```

## handle exclusions

```{r}
d <- d %>%
  filter(exclude_participant==0)
sampling_data <- sampling_data  %>%
  filter(exclude_participant==0)
test_array_clean <- test_array_clean %>%
  filter(exclude_participant==0)
test_array_options_clean <- test_array_options_clean %>%
  filter(exclude_participant==0)
```


## Summarize Test Data

```{r}
## shorter test representation
subj_test_accuracy <- test_array_clean %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  summarize(
    total_choices = n(),
    ground_truth_correct_choices = sum(test_choice_type_label_consistent),
    ground_truth_incorrect_choices = sum(test_choice_type_label_consistent==0),
    training_consistent_choices = sum(test_choice_type_training_consistent),
    training_inconsistent_choices = sum(test_choice_type_training_consistent==0),
    training_category_match_subordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "subordinate"),
    training_category_match_basic_choices = sum(test_choice_match_category==1 & test_choice_type == "basic"),
    training_category_match_superordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "superordinate"),
    training_category_match_subordinate_percent = training_category_match_subordinate_choices/2,
    training_category_match_basic_percent = training_category_match_basic_choices/2,
    training_category_match_superordinate_percent = training_category_match_superordinate_choices/4
  )

subj_test_accuracy_long <- subj_test_accuracy %>%
  select(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options,training_category_match_subordinate_percent,training_category_match_basic_percent,training_category_match_superordinate_percent) %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  pivot_longer(cols=training_category_match_subordinate_percent:training_category_match_superordinate_percent,names_to = "choice_type",values_to = "percent_chosen")

#combine with sampling data
subj_test_accuracy_long <- subj_test_accuracy_long %>%
  left_join(sampling_data)

overall_accuracy <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(current_category_training_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(current_category_training_level,current_category_label_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level_sampling <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(sampling_choice_narrowly_constraining,current_category_training_level,current_category_label_level,choice_type,) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

### longer test representation
subj_test_accuracy_all <- test_array_options_clean %>%
  group_by(subject,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options_label,total_number_correct_options_training) %>%
  summarize(
    accuracy_training = mean(is_match_to_training, na.rm=TRUE),
    accuracy_label = mean(is_match_to_label,na.rm=TRUE),
    hit_rate_training = mean(hit_training,na.rm=TRUE),
    hit_rate_label = mean(hit_label,na.rm=TRUE),
    false_alarm_rate_training = mean(false_alarm_training,na.rm=TRUE),
    false_alarm_rate_label = mean(false_alarm_label,na.rm=TRUE)
  ) %>%
  mutate(
    hit_rate_training_adj= case_when(
      hit_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      hit_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      TRUE ~ hit_rate_training
    ),
    hit_rate_label_adj= case_when(
      hit_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      hit_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      TRUE ~ hit_rate_label
    ),
    false_alarm_rate_training_adj= case_when(
      false_alarm_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      false_alarm_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      TRUE ~ false_alarm_rate_training
    ),
    false_alarm_rate_label_adj= case_when(
      false_alarm_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      false_alarm_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      TRUE ~ false_alarm_rate_label
    )
  ) %>%
  mutate(
    dprime_training=qnorm(hit_rate_training_adj) - qnorm(false_alarm_rate_training_adj),
    dprime_label=qnorm(hit_rate_label_adj) - qnorm(false_alarm_rate_label_adj),
    c_training=-.5*(qnorm(hit_rate_training_adj) + qnorm(false_alarm_rate_training_adj)),
    c_label=-.5*(qnorm(hit_rate_label_adj) + qnorm(false_alarm_rate_label_adj)))

subj_test_accuracy_all <- subj_test_accuracy_all %>%
  left_join(sampling_data)

overall_accuracy_label_level_sampling_all <- subj_test_accuracy_all %>%
  ungroup() %>%
  group_by(sampling_choice_narrowly_constraining,current_category_training_level,current_category_label_level) %>%
  summarize(
    N=n(),
    average_dprime_training=mean(dprime_training),
    average_dprime_label=mean(dprime_label)
  ) 
```

# Descriptive Plots

## Sampling

```{r}
sampling_data$sampled_category_level_kind_info_ord <- factor(sampling_data$sampled_category_level_kind_info,levels=c("sub","bas","sup","outside_category"))

sampling_data$current_category_training_level_ord <- factor(sampling_data$current_category_training_level,levels=c("narrow","intermediate","broad"))

ggplot(sampling_data,aes(x=sampled_category_level_kind_info_ord,color=within_category_sample_f,fill=within_category_sample_f))+
  geom_histogram(stat="count")+
  scale_fill_brewer(type="qual",palette="Set1")+
  scale_color_brewer(type="qual",palette="Set1")+
  facet_wrap(~current_category_training_level_ord)+
  scale_x_discrete(
    name = "Sampled Category Level",
    labels = c("subordinate","basic","superordinate","other category")
  )+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))+
  theme(legend.position="none")+
  ylab("Number of Choices")

ggsave(here(figure_path,"overall_sampling.pdf"))

ggplot(sampling_data,aes(x=sampled_category_level_kind_info_ord,color=within_category_sample_f,fill=within_category_sample_f))+
  geom_histogram(stat="count")+
  scale_fill_brewer(type="qual",palette="Set1")+
  scale_color_brewer(type="qual",palette="Set1")+
  facet_wrap(~current_category_training_level_ord+current_category_kind)+
  scale_x_discrete(
    name = "Sampled Category Level",
    labels = c("subordinate","basic","superordinate","other category")
  )+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))+
  theme(legend.position="none")+
  ylab("Number of Choices")
```

## Test

```{r}
overall_accuracy$choice_type_ord <- factor(overall_accuracy$choice_type,levels=c("subordinate","basic","superordinate"))

overall_accuracy$current_category_training_level_ord <- factor(overall_accuracy$current_category_training_level,levels=c("narrow","intermediate","broad"))

overall_accuracy_label_level$choice_type_ord <- factor(overall_accuracy_label_level$choice_type,levels=c("subordinate","basic","superordinate"))

overall_accuracy_label_level$current_category_label_level_ord <- factor(overall_accuracy_label_level$current_category_label_level,levels=c("narrow","intermediate","broad","hypernym"))

ggplot(overall_accuracy, aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p1 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="narrow"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p2 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="intermediate"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p3 <- ggplot(filter(overall_accuracy_label_level,current_category_training_level=="broad"), aes(choice_type_ord,average_percent))+
  geom_bar(stat="identity")+
  facet_wrap(~current_category_training_level+current_category_label_level_ord)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

plot_grid(p1,p2,p3,nrow=3)
  
```

## Sampling & Test

```{r}
ggplot(subj_test_accuracy_all,aes(sampling_choice_narrowly_constraining,dprime_training))+
  geom_boxplot()+
  geom_point()+
  facet_wrap(~current_category_training_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(subj_test_accuracy_all,aes(sampling_choice_narrowly_constraining,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(subj_test_accuracy_all,aes(sampling_choice_narrowly_constraining,accuracy_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(overall_accuracy_label_level_sampling_all,aes(sampling_choice_narrowly_constraining,average_dprime_training))+
  geom_boxplot()+
  geom_point()+
  facet_wrap(~current_category_training_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(overall_accuracy_label_level_sampling_all,aes(sampling_choice_narrowly_constraining,average_dprime_label))+
  geom_boxplot()+
  geom_point()+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p1 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="narrow"),aes(sampling_choice_narrowly_constraining,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p2 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="intermediate"),aes(sampling_choice_narrowly_constraining,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p3 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="broad"),aes(sampling_choice_narrowly_constraining,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p1 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="narrow"),aes(sampling_choice_narrowly_constraining,accuracy_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p2 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="intermediate"),aes(sampling_choice_narrowly_constraining,accuracy_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p3 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="broad"),aes(sampling_choice_narrowly_constraining,accuracy_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

ggplot(subj_test_accuracy_all,aes(sampling_choice_narrowly_constraining,accuracy_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))



p1 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="narrow"),aes(sampling_choice_consistent,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p2 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="intermediate"),aes(sampling_choice_consistent,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))

p3 <- ggplot(filter(subj_test_accuracy_all,current_category_training_level=="broad"),aes(sampling_choice_consistent,dprime_label))+
  geom_boxplot()+
  geom_jitter(alpha=0.2)+
  facet_wrap(~current_category_training_level+current_category_label_level)+
  theme_cowplot()+
  theme(axis.title = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12))
```

## Models

### Sampling

```{r}
#consistent
m <- glmer(sampling_choice_consistent_b~offset(logit(chance_consistent))+(1|subject), data=sampling_data, family=binomial)
summary(m)

m <- glmer(sampling_choice_consistent_b~offset(logit(chance_consistent))+current_category_training_level+(1|subject), data=sampling_data, family=binomial)
summary(m)
Anova(m,type="III")

ggplot(sampling_data,aes(current_category_training_level_ord,sampling_choice_consistent_b))+
  stat_summary()

#constraining
m <- glmer(sampling_choice_narrow_constraining_b~offset(logit(chance_narrowly_constraining))+(1|subject), data=sampling_data, family=binomial)
summary(m)

m <- glmer(sampling_choice_narrow_constraining_b~offset(logit(chance_narrowly_constraining))+current_category_training_level+(1|subject), data=sampling_data, family=binomial)
summary(m)
Anova(m,type="III")

m <- glmer(sampling_choice_narrow_constraining_b~offset(logit(chance_narrowly_constraining))+(1|subject), data=filter(sampling_data,current_category_training_level != "broad"), family=binomial)
summary(m)

ggplot(sampling_data,aes(current_category_training_level_ord,sampling_choice_narrow_constraining_b))+
  stat_summary()+
  facet_wrap(~current_category_kind)

ggplot(sampling_data,aes(current_category_training_level_ord,fill=sampling_choice_narrowly_constraining))+
  geom_bar(position="fill")

ggplot(sampling_data,aes(current_category_training_level_ord,fill=sampled_category_level_kind_info_ord))+
  geom_bar(position="fill")

subj_sampling <- sampling_data %>%
  group_by(subject) %>%
  summarize(
    mean_consistent=mean(sampling_choice_consistent_b),
    mean_narrowly_constraining = mean(sampling_choice_narrow_constraining_b),
    mean_outside_category=mean(sampled_category_level_kind_info=="outside_category"))

subj_test_accuracy_all <- subj_test_accuracy_all %>%
  left_join(subj_sampling)

ggplot(subj_test_accuracy_all,aes(mean_consistent,dprime_label))+
  geom_point()+
  geom_smooth(method="lm",se=FALSE,aes(color=current_category_training_level))+
  geom_smooth(method="lm")

m <- lmer(dprime_label~ mean_consistent+(1+mean_consistent|subject),data=subj_test_accuracy_all)
summary(m)

ggplot(subj_test_accuracy_all,aes(mean_narrowly_constraining,dprime_label))+
  geom_point()+
  geom_smooth(method="lm",se=FALSE,aes(color=current_category_training_level))+
  geom_smooth(method="lm")

m <- lmer(dprime_label~ mean_narrowly_constraining+(1+mean_narrowly_constraining|subject),data=subj_test_accuracy_all)
summary(m)

ggplot(subj_test_accuracy_all,aes(mean_outside_category,dprime_label))+
  geom_point()+
  geom_smooth(method="lm",se=FALSE,aes(color=current_category_training_level))+
  geom_smooth(method="lm")

m <- lmer(dprime_label~ mean_outside_category+(1+mean_outside_category|subject),data=subj_test_accuracy_all)
summary(m)


```


### Test

```{r}
m <- glmer(is_chosen ~ current_category_training_level + current_category_kind + (1+current_category_training_level|subject)+(1|test_image), data=test_array_options,family=binomial)
summary(m)
Anova(m,type="III")

m <- glmer(is_chosen ~ current_category_training_level * current_category_label_level * current_category_kind + (1|subject)+(1|test_image), data=test_array_options,family=binomial)
summary(m)
Anova(m,type="III")
```

### Sampling Test

```{r}
m <- lmer(accuracy_label~1+sampling_choice_narrowly_constraining+(1+sampling_choice_narrowly_constraining|subject),data=filter(subj_test_accuracy_all,sampling_choice_narrowly_constraining!="inconsistent"))
summary(m)

m <- glmer(is_match_to_label~1+sampling_choice_narrowly_constraining+(1+sampling_choice_narrowly_constraining|subject),data=filter(test_array_options_clean,sampling_choice_narrowly_constraining!="inconsistent"),family=binomial)
summary(m)

m <- glmer(is_match_to_label~1+sampling_choice_consistent+(1+sampling_choice_consistent|subject),data=test_array_options_clean,family=binomial)
summary(m)

m <- glmer(is_match_to_label~1+sampling_choice_consistent*current_category_training_level+(1+sampling_choice_consistent*current_category_training_level|subject),data=test_array_options_clean,family=binomial)
summary(m)
```

